### ISSUE TITLE
Nav bar seems off on Chromium 40

### ISSUE THREAD

**Issue by jpetazzo** [docker/docs-base#8] opened 2015-04-11 13:53 UTC
The login buttons seem weirdly placed:

![image](https://cloud.githubusercontent.com/assets/171481/7101634/39e8c846-e017-11e4-9241-9c836815a15c.png)

User-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

Shows correctly on Iceweasel.

Let me know if there is something help that could help.

**Comment by thaJeztah** [comment] 2015-04-11 14:12
I've been tracking some similar rendering issues with Jess some time ago (see https://github.com/docker/docker/issues/10007). For what I was able to find, this seemed to be caused by differences in font rendering between Linux and Windows/OS X. That, in combination with the layout being a bit brittle because the use of "float", which causes elements to "wrap" if they are rendered larger because of font-rendering differences.

It's a bit hard for me to look into it, because I don't have a linux desktop around to reproduce. Perhaps the "float" usage can be tweaked a bit to make it less brittle.

**Comment by moxiegirl** [comment] 2015-04-11 14:55
Yeah, I don't see this problem on Mac Chrome (Version 41.0.2272.118 (64-bit)) or Safari.  We need to do more user testing but we are also getting ready redo the look and feel for Dockercon.  Given how we aren't getting tons of issues on this, might be best to just wait.  (And noted we need better cross-browser testing before we release. I know a tool that works for this but taking suggestions as well.)

![image](https://cloud.githubusercontent.com/assets/1347209/7101837/e21550b8-e01f-11e4-9c23-750b840ac161.png)

**Comment by thaJeztah** [comment] 2015-04-11 15:07
Browserstack has quite an extensive live of browsers; https://www.browserstack.com/list-of-browsers-and-platforms?product=live no Linux, though (possibly because configurations can widely vary there).

Though, a good template/skin should be able to handle most setups.

**Comment by thaJeztah** [comment] 2016-02-11 11:04
This is about the old design/layout; I'll close this

**Closed by thaJeztah** 2016-02-11 11:04 UTC
