### ISSUE TITLE
User feedback from feedback@docker.com

### ISSUE THREAD

**Issue by j0hnst0n** [docker/docs-base#62] opened 2015-06-22 12:39 UTC
![image](https://cloud.githubusercontent.com/assets/1610391/8281871/eb92c580-18a0-11e5-86fb-9b79d18c119f.png)

**Comment by moxiegirl** [comment] 2015-06-29 17:42
- The mini toc was aded in this weekend. Closed by PR #90
- Fonts and look and feel were tweaked but we are pending design resources. The problem is addressed in https://github.com/docker/docs-base/issues/69 make this a dup.  
- Closing as fixed/dup.

**Closed by moxiegirl** 2015-06-29 17:42 UTC
